### ISSUE TITLE
IndexError in overrides api with Python 3.6

### ISSUE THREAD

**Issue by fabriciorsf** [pdasigi/neural-event-model#2]
I get this error with stable newest python (3.6):
```shell
Traceback (most recent call last):
  File "......./neural-event-model/nem.py", line 17, in <module>
    from keras_extensions import AnyShapeEmbedding, TimeDistributedRNN, MaskedFlatten
  File "......./neural-event-model/keras_extensions.py", line 11, in <module>
    class AnyShapeEmbedding(Embedding):
  File "......./neural-event-model/keras_extensions.py", line 16, in AnyShapeEmbedding
    @overrides
  File "......./lib/python3.6/site-packages/overrides/overrides.py", line 58, in overrides
    for super_class in _get_base_classes(sys._getframe(2), method.__globals__):
  File "......./lib/python3.6/site-packages/overrides/overrides.py", line 75, in _get_base_classes
    class_name_components in _get_base_class_names(frame)]
  File "......./lib/python3.6/site-packages/overrides/overrides.py", line 96, in _get_base_class_names
    if type(co.co_consts[oparg]) == str:
IndexError: tuple index out of range
```

It's like that link: https://github.com/mkorpela/overrides/issues/11

**Comment by pdasigi** [comment]
Clearly it's still an open issue with overrides. May be eliminate dependency on it completely? It is used only [here](https://github.com/pdasigi/neural-event-model/blob/master/keras_extensions.py#L16) and [here](https://github.com/pdasigi/neural-event-model/blob/master/keras_extensions.py#L28).

**Comment by fabriciorsf** [comment]
Yes, I eliminated the dependency and I guess it worked for me... thanks!
I commented the follows lines: [keras_extencions.py:5](https://github.com/pdasigi/neural-event-model/blob/master/keras_extensions.py#L5), [keras_extencions.py:16](https://github.com/pdasigi/neural-event-model/blob/master/keras_extensions.py#L16) and [keras_extencions.py:28](https://github.com/pdasigi/neural-event-model/blob/master/keras_extensions.py#L28).
